In [1]:
import pandas as pd

In [2]:
db_data = pd.read_csv("uniprotlinks.csv")

In [3]:
col = db_data["UniProt ID"]

In [4]:
import mygene

In [5]:
mg = mygene.MyGeneInfo()

In [6]:
out = mg.querymany(col, scopes='uniprot', fields='symbol', species='human', returnall=True, as_dataframe=True)

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-16168...done.
Finished.
1297 input query terms found dup hits:
	[('P00734', 102), ('P00533', 23), ('O75015', 19), ('P00736', 20), ('P02745', 18), ('P02746', 18), ('
4207 input query terms found no hit:
	['Q53I07', 'P13843', 'Q2TU84', 'Q49AK1', 'Q53ET4', 'Q59GM9', 'Q59HE2', 'Q6IBS8', 'Q9BXA1', 'Q9UGI5',

In [7]:
out['out']

           _id     _score notfound    symbol
query
P00734    2147  20.186922      NaN        F2
P00533    1956  19.741434      NaN      EGFR
O75015    2215  20.188843      NaN    FCGR3B
P00736     715  21.690075      NaN       C1R
P02745     712  22.844710      NaN      C1QA
P02746     713  21.668577      NaN      C1QB
P02747     714  20.825530      NaN      C1QC
P08637    2214  20.264400      NaN    FCGR3A
P09871     716  21.667978      NaN       C1S
P12314    2209  21.633108      NaN    FCGR1A
P12318    2212  20.816162      NaN    FCGR2A
P31994    2213  12.627164      NaN    FCGR2B
P31995    2213  13.025829      NaN    FCGR2B
P31995    9103   6.721117      NaN    FCGR2C
P01589    3559  20.821302      NaN     IL2RA
P14784    3560  21.648472      NaN     IL2RB
P31785    3561  20.867012      NaN     IL2RG
P01375    7124  20.216599      NaN       TNF
P20333    7133  20.845577      NaN  TNFRSF1B
P12314    2209  21.639082      NaN    FCGR1A
P08637    2214  20.264400      NaN    FCGR3A
P12318    2212  20.814238      NaN    FCGR2A
P31994    2213  13.025731      NaN    FCGR2B
P31995    2213  12.635159      NaN    FCGR2B
P31995    9103   6.721219      NaN    FCGR2C
P01374    4049  20.203463      NaN       LTA
O75015    2215  20.814238      NaN    FCGR3B
P09871     716  21.668620      NaN       C1S
P00736     715  21.662971      NaN       C1R
P02745     712  22.817322      NaN      C1QA
...        ...        ...      ...       ...
P28566    3354  21.660152      NaN     HTR1E
P30939    3355  21.648472      NaN     HTR1F
P28223    3356  20.826956      NaN     HTR2A
P41595    3357  21.644236      NaN     HTR2B
P28335    3358  20.837175      NaN     HTR2C
P46098    3359  20.842518      NaN     HTR3A
O95264    9177  20.835463      NaN     HTR3B
Q8WXA8  170572  20.830822      NaN     HTR3C
Q70Z44  200909  20.835777      NaN     HTR3D
A5X5Y0  285242  20.816162      NaN     HTR3E
Q13639    3360  20.807530      NaN      HTR4
P50406    3362  21.670715      NaN      HTR6
P34969    3363  21.633108      NaN      HTR7
P35348     148  20.264400      NaN    ADRA1A
P35368     147  20.822311      NaN    ADRA1B
P25100     146  21.644236      NaN    ADRA1D
P08913     150  20.810205      NaN    ADRA2A
P18089     151  20.891918      NaN    ADRA2B
P18825     152  20.889854      NaN    ADRA2C
P35367    3269  21.668620      NaN      HRH1
P07550     154  20.220090      NaN     ADRB2
Q99062    1441  20.816162      NaN     CSF3R
P13726    2152  20.826956      NaN        F3
P00742    2159  21.668577      NaN       F10
P00740    2158  20.245193      NaN        F9
P10275     367  20.213787      NaN        AR
P04150    2908  20.844564      NaN     NR3C1
P00533    1956  19.741434      NaN      EGFR
P12821    1636  20.862978      NaN       ACE
P33402    2977  21.665508      NaN   GUCY1A2

[16310 rows x 4 columns]

In [8]:
print(type(out))

<class 'dict'>

In [9]:
print(db_data.head())

  DrugBank ID       Name         Type UniProt ID  \
0     DB00001  Lepirudin  BiotechDrug     P00734
1     DB00002  Cetuximab  BiotechDrug     P00533
2     DB00002  Cetuximab  BiotechDrug     O75015
3     DB00002  Cetuximab  BiotechDrug     P00736
4     DB00002  Cetuximab  BiotechDrug     P02745

                                        UniProt Name
0                                        Prothrombin
1                   Epidermal growth factor receptor
2  Low affinity immunoglobulin gamma Fc region re...
3                        Complement C1r subcomponent
4              Complement C1q subcomponent subunit A

In [10]:
for key in out:
    print(key)

out
dup
missing

In [11]:
#turning the dictionary into a string. 

dict_ = out["out"].astype(str)

In [12]:
print(dict_.head())

         _id     _score notfound  symbol
query
P00734  2147  20.186922      nan      F2
P00533  1956  19.741434      nan    EGFR
O75015  2215  20.188843      nan  FCGR3B
P00736   715  21.690075      nan     C1R
P02745   712   22.84471      nan    C1QA

In [13]:
print(type(dict_))

<class 'pandas.core.frame.DataFrame'>

In [14]:
col_names = dict_.columns.values

In [15]:
print(col_names)

['_id' '_score' 'notfound' 'symbol']

In [16]:
#renaming column names in df_2. 

df_2 = dict_.rename(columns={'symbol': 'Gene Symbol'})

In [17]:
print(df_2.head())

         _id     _score notfound Gene Symbol
query
P00734  2147  20.186922      nan          F2
P00533  1956  19.741434      nan        EGFR
O75015  2215  20.188843      nan      FCGR3B
P00736   715  21.690075      nan         C1R
P02745   712   22.84471      nan        C1QA

In [18]:
#deleting a column 'notfound' from df_2.  

del df_2['notfound']

In [19]:
del df_2['_id']

In [20]:
print(df_2.head())

           _score Gene Symbol
query
P00734  20.186922          F2
P00533  19.741434        EGFR
O75015  20.188843      FCGR3B
P00736  21.690075         C1R
P02745   22.84471        C1QA

In [24]:
##finding duplicated index. 

df_2[df_2.index.duplicated()]

           _score Gene Symbol
query
P31995   6.721117      FCGR2C
P12314  21.639082      FCGR1A
P08637    20.2644      FCGR3A
P12318  20.814238      FCGR2A
P31994  13.025731      FCGR2B
P31995  12.635159      FCGR2B
P31995  6.7212186      FCGR2C
O75015  20.814238      FCGR3B
P09871   21.66862         C1S
P00736  21.662971         C1R
P02745  22.817322        C1QA
P02746  21.667564        C1QB
P02747  20.837175        C1QC
P00734  20.188843          F2
P48551   21.71505      IFNAR2
P17181  21.694685      IFNAR1
P00747  20.847492         PLG
Q03405  21.649942       PLAUR
P05121   20.22009    SERPINE1
P30968  20.822311       GNRHR
P00747  20.847492         PLG
P02671   20.80753         FGA
Q03405  21.666986       PLAUR
P05121  20.218222    SERPINE1
P19235  20.212605        EPOR
P17181  21.694685      IFNAR1
P48551  21.697561      IFNAR2
P17181  21.662971      IFNAR1
P48551   21.71505      IFNAR2
P12314  21.633108      FCGR1A
...           ...         ...
P28566  21.660152       HTR1E
P30939  21.648472       HTR1F
P28223  20.826956       HTR2A
P41595  21.644236       HTR2B
P28335  20.837175       HTR2C
P46098  20.842518       HTR3A
O95264  20.835463       HTR3B
Q8WXA8  20.830822       HTR3C
Q70Z44  20.835777       HTR3D
A5X5Y0  20.816162       HTR3E
Q13639   20.80753        HTR4
P50406  21.670715        HTR6
P34969  21.633108        HTR7
P35348    20.2644      ADRA1A
P35368  20.822311      ADRA1B
P25100  21.644236      ADRA1D
P08913  20.810205      ADRA2A
P18089  20.891918      ADRA2B
P18825  20.889854      ADRA2C
P35367   21.66862        HRH1
P07550   20.22009       ADRB2
Q99062  20.816162       CSF3R
P13726  20.826956          F3
P00742  21.668577         F10
P00740  20.245193          F9
P10275  20.213787          AR
P04150  20.844564       NR3C1
P00533  19.741434        EGFR
P12821  20.862978         ACE
P33402  21.665508     GUCY1A2

[12222 rows x 2 columns]